#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

service: fhir-service

custom:
  oldResourceTableName: 'resource-${self:custom.stage}'
  resourceTableName: 'resource-db-${self:custom.stage}'
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  oauthRedirect: ${opt:oauthRedirect, 'http://localhost'}
  config: ${file(serverless_config.json)}

provider:
  name: aws
  region: us-west-2
  stage: dev
  runtime: nodejs12.x
  memorySize: 512
  logRetentionInDays: 90
  stackTags:
    FHIR_SERVICE: 'fhir-service-${self:custom.region}-${self:custom.stage}'
  environment:
    API_URL:
      !Join ['', ['https://', !Ref ApiGatewayRestApi, !Sub '.execute-api.${AWS::Region}.amazonaws.com/', !Ref Stage]]
    S3_KMS_KEY: !Ref S3KMSKey
    RESOURCE_TABLE: !Ref ResourceDynamoDBTableV2
    FHIR_BINARY_BUCKET: !Ref FHIRBinaryBucket
    ELASTICSEARCH_DOMAIN_ENDPOINT: !Join ['', ['https://', !GetAtt ElasticSearchDomain.DomainEndpoint]]
    OAUTH2_DOMAIN_ENDPOINT:
      !Join ['', ['https://', !Ref UserPoolDomain, !Sub '.auth.${AWS::Region}.amazoncognito.com/oauth2']]
  apiKeys:
    - name: 'developer-key-${self:custom.stage}' # Full name must be known at package-time
      description: Key for developer to access the FHIR Api
  usagePlan:
    throttle:
      burstLimit: 100 # maximum API request rate limit over a time ranging from one to a few seconds
      rateLimit: 50 # average requests per second over an extended period of time
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._@'\",\\-\\/\\(\\)]+?)}" # Use this for allowing CloudFormation Pseudo-Parameters in your serverless.yml
  logs:
    restApi:
      executionLogging: true
      fullExecutionData: true
      accessLogging: true
  tracing:
    apiGateway: true
    lambda: true

functions:
  fhirServer:
    timeout: 40
    description: 'FHIR API Server'
    role: FhirServerLambdaRole
    events:
      - http:
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
            scopes: # must have both scopes
              - 'openid'
              - 'profile'
              - 'aws.cognito.signin.user.admin'
          method: ANY
          path: /
          private: true
      - http:
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
            scopes: # must have both scopes
              - 'openid'
              - 'profile'
              - 'aws.cognito.signin.user.admin'
          method: ANY
          path: '{proxy+}'
          private: true
      - http:
          method: GET
          path: /metadata
    handler: src/index.default
    provisionedConcurrency: 5

  ddbToEs:
    timeout: 300
    runtime: nodejs12.x
    description: 'Write DDB changes from `resource` table to ElasticSearch service'
    role: DdbToEsLambdaRole
    handler: ddbToEsLambda/index.handler
    events:
      - stream:
          type: dynamodb
          arn:
            'Fn::GetAtt':
              - ResourceDynamoDBTableV2
              - StreamArn
          batchSize: 100
          maximumRetryAttempts: 3
          startingPosition: LATEST

resources:
  - Description: (SO0128) - Solution - Primary Template - This template creates all the necessary resources to deploy FHIR Works on AWS; a framework to deploy a FHIR server on AWS.
  - Parameters:
      Stage:
        Type: String
        Default: ${self:custom.stage}
        Description: 'Stage must be "dev"'
        ConstraintDescription: 'Must be "dev"'
        AllowedValues:
          - dev
      CognitoOAuthDefaultRedirectURL:
        Type: String
        Default: ${self:custom.oauthRedirect}
        Description: "Cognito's default OAuth redirect URL used for User Pool. Default: ${self:custom.oauthRedirect}"
  - Conditions:
      isDev: !Equals [!Ref Stage, 'dev']
      isNotDev: !Not [Condition: isDev]
  - Resources:
      ResourceDynamoDBTableV2:
        Metadata:
          cfn_nag:
            rules_to_suppress:
              - id: W28
                reason: 'We want to set the table explicit name'
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
          TableName: ${self:custom.resourceTableName}
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
            - AttributeName: vid
              AttributeType: N
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: vid
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
          PointInTimeRecoverySpecification:
            PointInTimeRecoveryEnabled: true
          StreamSpecification:
            StreamViewType: NEW_AND_OLD_IMAGES
          SSESpecification:
            KMSMasterKeyId: !Ref DynamodbKMSKey
            SSEEnabled: true
            SSEType: 'KMS'
          Tags: !If
            - isNotDev
            - - Key: 'backup' # You must also cfn deploy backup.yaml to enable back-ups
                Value: 'daily'
              - Key: 'service'
                Value: 'fhir'
            - Ref: AWS::NoValue
      ApiGatewayAuthorizer:
        Type: AWS::ApiGateway::Authorizer
        Properties:
          AuthorizerResultTtlInSeconds: 300
          IdentitySource: method.request.header.Authorization
          RestApiId:
            Ref: ApiGatewayRestApi
          Type: COGNITO_USER_POOLS
          Name: Authorizer
          ProviderARNs:
            - !Join [
                '',
                [!Sub 'arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/', !Ref UserPool],
              ]
      FHIRBinaryBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Properties:
          LoggingConfiguration:
            DestinationBucketName: !Ref FHIRLogsBucket
            LogFilePrefix: 'binary-acl'
          VersioningConfiguration:
            Status: Enabled
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: aws:kms
                  KMSMasterKeyID: !Ref S3KMSKey
      FHIRLogsBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
        Metadata:
          cfn_nag:
            rules_to_suppress:
              - id: W51
                reason: 'This is the logs bucket'
              - id: W35
                reason: 'This is the logs bucket'
        Properties:
          AccessControl: LogDeliveryWrite
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: aws:kms
                  KMSMasterKeyID: !Ref S3KMSKey
      FHIRBinaryBucketHttpsOnlyPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket: !Ref FHIRBinaryBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowSSLRequestsOnly
                Effect: Deny
                Principal: '*'
                Action:
                  - s3:*
                Resource:
                  - !GetAtt FHIRBinaryBucket.Arn
                  - !Join ['', [!GetAtt FHIRBinaryBucket.Arn, '/*']]
                Condition:
                  Bool:
                    'aws:SecureTransport': false
      FhirServerLambdaRole:
        Type: AWS::IAM::Role
        Metadata:
          cfn_nag:
            rules_to_suppress:
              - id: W11
                reason: 'Only applies to X-Ray statement which does not define a group or sampling-rule'
              - id: W76
                reason: 'SPCM higher than 25 is justified'
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Principal:
                  Service: 'lambda.amazonaws.com'
                Action: 'sts:AssumeRole'
          Policies:
            - PolicyName: 'FhirServerLambdaPolicy'
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogStream
                      - logs:CreateLogGroup
                      - logs:PutLogEvents
                    Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:*:*'
                  - Effect: Allow
                    Action:
                    - 'kms:Describe*'
                    - 'kms:Get*'
                    - 'kms:List*'
                    - 'kms:Encrypt'
                    - 'kms:Decrypt'
                    - 'kms:ReEncrypt*'
                    - 'kms:GenerateDataKey'
                    - 'kms:GenerateDataKeyWithoutPlaintext'
                    Resource:
                      - !GetAtt S3KMSKey.Arn
                      - !GetAtt DynamodbKMSKey.Arn
                      - !GetAtt ElasticSearchKMSKey.Arn
                  - Effect: Allow
                    Action:
                    - 'dynamodb:Query'
                    - 'dynamodb:Scan'
                    - 'dynamodb:GetItem'
                    - 'dynamodb:PutItem'
                    - 'dynamodb:UpdateItem'
                    - 'dynamodb:DeleteItem'
                    - 'dynamodb:BatchWriteItem'
                    Resource:
                      - !GetAtt ResourceDynamoDBTableV2.Arn
                  - Effect: Allow
                    Action:
                      - 'es:ESHttpHead'
                      - 'es:ESHttpGet'
                      - 'es:ESHttpPost'
                    Resource:
                      - !Join ['', [!GetAtt ElasticSearchDomain.Arn, '/*']]
                  - Effect: Allow
                    Action:
                      - 's3:*Object'
                      - 's3:ListBucket'
                      - 's3:DeleteObjectVersion'
                    Resource:
                      - !GetAtt FHIRBinaryBucket.Arn
                      - !Join ['', [!GetAtt FHIRBinaryBucket.Arn, '/*']]
                  - Effect: Allow
                    Action:
                      - 'xray:PutTraceSegments'
                      - 'xray:PutTelemetryRecords'
                    Resource:
                      - '*'
      DdbToEsLambdaRole:
        Type: AWS::IAM::Role
        Metadata:
          cfn_nag:
            rules_to_suppress:
              - id: W11
                reason: 'Wildcard is only present on CloudWatch log stream resource'
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Principal:
                  Service: 'lambda.amazonaws.com'
                Action: 'sts:AssumeRole'
          Policies:
            - PolicyName: 'DdbToEsLambdaPolicy'
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - logs:CreateLogStream
                      - logs:CreateLogGroup
                      - logs:PutLogEvents
                    Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:*:*'
                  - Effect: Allow
                    Action:
                      - dynamodb:GetShardIterator
                      - dynamodb:DescribeStream
                      - dynamodb:ListStreams
                      - dynamodb:GetRecords
                    Resource:
                      - !GetAtt ResourceDynamoDBTableV2.StreamArn
                  - Effect: Allow
                    Action:
                      - xray:PutTraceSegments
                      - xray:PutTelemetryRecords
                    Resource:
                      - '*'
                  - Effect: Allow
                    Action:
                      - 'es:ESHttp*'
                    Resource:
                      - !Join ['', [!GetAtt ElasticSearchDomain.Arn, '/*']]
            - PolicyName: 'KMSPolicy'
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - 'kms:Describe*'
                      - 'kms:Get*'
                      - 'kms:List*'
                      - 'kms:Encrypt'
                      - 'kms:Decrypt'
                      - 'kms:ReEncrypt*'
                      - 'kms:GenerateDataKey'
                      - 'kms:GenerateDataKeyWithoutPlaintext'
                    Resource:
                      - !GetAtt DynamodbKMSKey.Arn
                      - !GetAtt ElasticSearchKMSKey.Arn
  - extensions:
      FhirServerLogGroup:
        Properties:
          KmsKeyId: !GetAtt LogKMSKey.Arn
        DependsOn:
          - LogKMSKey
      DdbToEsLogGroup:
        Properties:
          KmsKeyId: !GetAtt LogKMSKey.Arn
        DependsOn:
          - LogKMSKey
      ApiGatewayLogGroup:
        Properties:
          KmsKeyId: !GetAtt LogKMSKey.Arn
        DependsOn:
          - LogKMSKey
  - ${file(cloudformation/alarms.yaml)}
  - ${file(cloudformation/kms.yaml)}
  - ${file(cloudformation/elasticsearch.yaml)}
  - ${file(cloudformation/cognito.yaml)}
  - Outputs:
      UserPoolId:
        Description: User pool id for the provisioning users.
        Value: !Ref UserPool
      UserPoolAppClientId:
        Description: App client id for the provisioning users.
        Value: !Ref UserPoolClient
      FHIRBinaryBucket:
        Description: S3 Bucket for storing Binary Objects
        Value: !Ref FHIRBinaryBucket
      ElasticSearchDomainEndpoint:
        Description: Endpoint of ElasticSearch instance
        Value: !Join ['', ['https://', !GetAtt ElasticSearchDomain.DomainEndpoint]]
      ElasticSearchDomainKibanaEndpoint:
        Condition: isDev
        Description: ElasticSearch Kibana endpoint
        Value: !Join ['', ['https://', !GetAtt ElasticSearchDomain.DomainEndpoint, '/_plugin/kibana']]
      ElasticSearchKibanaUserPoolId:
        Condition: isDev
        Description: User pool id for the provisioning ES Kibana users.
        Value: !Ref KibanaUserPool
      ElasticSearchKibanaUserPoolAppClientId:
        Condition: isDev
        Description: App client id for the provisioning ES Kibana users.
        Value: !Ref KibanaUserPoolClient
      CloudwatchExecutionLogGroup:
        Description: Cloudwatch Execution log group for storing request/responses for auditing purposes
        Value: !Join ['', ['API-Gateway-Execution-Logs_', !Ref ApiGatewayRestApi, '/', !Ref Stage]]
        Export:
          Name: !Join ['-', [CloudwatchExecutionLogGroup, !Ref Stage]]
      CloudwatchExecutionLogGroupArn:
        Description: Arn of Cloudwatch Execution log group for storing request/responses for auditing purposes
        Value:
          !Join [
            '',
            [
              !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:API-Gateway-Execution-Logs_',
              !Ref ApiGatewayRestApi,
              '/',
              !Ref Stage,
              ':log-stream:*',
            ],
          ]
        Export:
          Name: !Join ['-', [CloudwatchExecutionLogGroup, !Ref Stage, Arn]]

plugins:
  - serverless-plugin-typescript
  - serverless-offline
